import React from 'react'
import { Download, FileText, FileJson, File } from 'lucide-react'

const ExportOptions = ({ report }) => {
  const exportAsPDF = () => {
    // Generate clean HTML for PDF
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Research Report</title>
        <style>
          @page { margin: 1in; }
          body {
            font-family: 'Times New Roman', Times, serif;
            font-size: 12pt;
            line-height: 2;
            color: #000;
            max-width: 8.5in;
            margin: 0 auto;
          }
          .title-page {
            text-align: center;
            margin: 3in 0 2in 0;
          }
          h1 {
            font-size: 18pt;
            font-weight: bold;
            text-transform: uppercase;
            margin-bottom: 1in;
          }
          .metadata {
            margin-top: 1in;
            line-height: 1.5;
          }
          h2 {
            font-size: 14pt;
            font-weight: bold;
            margin-top: 24pt;
            margin-bottom: 12pt;
            page-break-after: avoid;
          }
          h3 {
            font-size: 12pt;
            font-weight: bold;
            margin-top: 12pt;
            margin-bottom: 6pt;
          }
          p {
            text-align: justify;
            margin-bottom: 12pt;
            text-indent: 0.5in;
          }
          .abstract {
            margin: 24pt 0.5in;
            border-left: 3pt solid #333;
            padding-left: 12pt;
          }
          .abstract p {
            text-indent: 0;
          }
          .section {
            page-break-inside: avoid;
          }
          .page-break {
            page-break-after: always;
          }
        </style>
      </head>
      <body>
        ${formatReportForPDF(report)}
      </body>
      </html>
    `

    // Create blob and download
    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = 'research-report.html'
    a.click()
    URL.revokeObjectURL(url)

    alert('HTML file downloaded! Open it in your browser and use Print > Save as PDF to generate a professional PDF.')
  }

  const formatReportForPDF = (report) => {
    const cleanText = (text) => {
      return text
        .replace(/#{1,6}\s/g, '')
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        .replace(/`(.*?)`/g, '<code>$1</code>')
        .replace(/\n\n/g, '</p><p>')
    }

    const today = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    return `
      <div class="title-page">
        <h1>Research Report</h1>
        <div class="metadata">
          <p style="text-indent: 0;"><strong>Date:</strong> ${today}</p>
          <p style="text-indent: 0;"><strong>Generated by:</strong> Multi-Agent Research System</p>
          ${report.quality_score ? `<p style="text-indent: 0;"><strong>Quality Score:</strong> ${report.quality_score}/100</p>` : ''}
        </div>
      </div>
      
      <div class="page-break"></div>
      
      ${report.summaries?.executive ? `
        <div class="abstract section">
          <h2>ABSTRACT</h2>
          <p>${cleanText(report.summaries.executive)}</p>
        </div>
      ` : ''}
      
      <div class="section">
        <h2>MAIN REPORT</h2>
        <p>${cleanText(report.final_report || '')}</p>
      </div>
      
      ${report.summaries?.bullet ? `
        <div class="section">
          <h2>KEY FINDINGS</h2>
          <p>${cleanText(report.summaries.bullet)}</p>
        </div>
      ` : ''}
      
      ${report.fact_check_report ? `
        <div class="section">
          <h2>FACT CHECK REPORT</h2>
          <p>${cleanText(report.fact_check_report)}</p>
        </div>
      ` : ''}
    `
  }

  const exportAsMarkdown = () => {
    const content = `# Research Report\n\n${report.final_report}\n\n## Fact Check\n${report.fact_check_report || 'N/A'}`
    downloadFile(content, 'research-report.md', 'text/markdown')
  }

  const exportAsJSON = () => {
    const content = JSON.stringify(report, null, 2)
    downloadFile(content, 'research-report.json', 'application/json')
  }

  const downloadFile = (content, filename, type) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = filename
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="export-options">
      <div className="export-header">
        <Download size={24} />
        <h3>Export Report</h3>
      </div>
      <p className="export-description">Download your research report in different formats</p>
      <div className="export-buttons">
        <button onClick={exportAsPDF} className="export-btn pdf">
          <File size={20} />
          <span>
            <strong>Export as PDF</strong>
            <small>Professional academic format</small>
          </span>
        </button>
        <button onClick={exportAsMarkdown} className="export-btn markdown">
          <FileText size={20} />
          <span>
            <strong>Export as Markdown</strong>
            <small>Plain text with formatting</small>
          </span>
        </button>
        <button onClick={exportAsJSON} className="export-btn json">
          <FileJson size={20} />
          <span>
            <strong>Export as JSON</strong>
            <small>Raw data format</small>
          </span>
        </button>
      </div>

      <style>{`
        .export-options {
          background: white;
          border-radius: 12px;
          padding: 2rem;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
          margin: 2rem 0;
        }

        .export-header {
          display: flex;
          align-items: center;
          gap: 0.75rem;
          margin-bottom: 0.5rem;
          color: #667eea;
        }

        .export-header h3 {
          margin: 0;
          font-size: 1.5rem;
          color: #1f2937;
        }

        .export-description {
          color: #6b7280;
          margin-bottom: 1.5rem;
        }

        .export-buttons {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1rem;
        }

        .export-btn {
          display: flex;
          align-items: center;
          gap: 1rem;
          padding: 1.25rem;
          border: 2px solid #e5e7eb;
          border-radius: 8px;
          background: white;
          cursor: pointer;
          transition: all 0.2s;
          text-align: left;
        }

        .export-btn:hover {
          transform: translateY(-2px);
          box-shadow: 0 8px 16px rgba(0, 0, 0, 0.1);
        }

        .export-btn.pdf {
          border-color: #ef4444;
        }

        .export-btn.pdf:hover {
          background: #fef2f2;
          border-color: #dc2626;
        }

        .export-btn.markdown {
          border-color: #3b82f6;
        }

        .export-btn.markdown:hover {
          background: #eff6ff;
          border-color: #2563eb;
        }

        .export-btn.json {
          border-color: #10b981;
        }

        .export-btn.json:hover {
          background: #ecfdf5;
          border-color: #059669;
        }

        .export-btn svg {
          flex-shrink: 0;
        }

        .export-btn span {
          display: flex;
          flex-direction: column;
          gap: 0.25rem;
        }

        .export-btn strong {
          font-size: 1rem;
          color: #1f2937;
        }

        .export-btn small {
          font-size: 0.85rem;
          color: #6b7280;
        }

        @media (max-width: 768px) {
          .export-buttons {
            grid-template-columns: 1fr;
          }
        }
      `}</style>
    </div>
  )
}

export default ExportOptions