import React, { useState } from 'react'

const ReportViewer = ({ report }) => {
  const [view, setView] = useState('final') // final, summaries, fact_check

  console.log('ReportViewer rendered with report:', report ? 'YES' : 'NO')

  if (!report) return null

  // Function to convert markdown-style text to clean HTML
  const formatText = (text) => {
    if (!text) return ''

    // Remove markdown formatting
    let formatted = text
      .replace(/#{1,6}\s/g, '') // Remove heading markers
      .replace(/\*\*(.*?)\*\*/g, '$1') // Remove bold
      .replace(/\*(.*?)\*/g, '$1') // Remove italic
      .replace(/`(.*?)`/g, '$1') // Remove code marks
      .replace(/\[(.*?)\]\(.*?\)/g, '$1') // Remove links, keep text

    return formatted
  }

  // Parse the report into sections
  const parseReport = (text) => {
    if (!text) return { title: '', sections: [] }

    const lines = text.split('\n')
    let title = ''
    let currentSection = { heading: '', content: [] }
    const sections = []

    for (const line of lines) {
      const trimmed = line.trim()

      // Detect title (first non-empty line or line with # markers)
      if (!title && trimmed && trimmed.length > 0) {
        title = formatText(trimmed)
        continue
      }

      // Detect section headings
      if (trimmed.match(/^#{1,3}\s/) || (trimmed.length > 0 && trimmed.length < 100 && line.match(/^[A-Z]/))) {
        if (currentSection.content.length > 0) {
          sections.push(currentSection)
        }
        currentSection = { heading: formatText(trimmed), content: [] }
      } else if (trimmed.length > 0) {
        currentSection.content.push(formatText(trimmed))
      }
    }

    if (currentSection.content.length > 0) {
      sections.push(currentSection)
    }

    return { title, sections }
  }

  const renderFinalReport = () => {
    const { title, sections } = parseReport(report.final_report)
    const today = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    })

    return (
      <div className="research-paper">
        {/* Header */}
        <div className="paper-header">
          <h1 className="paper-title">{title || 'Research Report'}</h1>
          <div className="paper-meta">
            <p className="paper-date">{today}</p>
            <p className="paper-generated">Generated by Multi-Agent Research System</p>
            {report.quality_score && (
              <p className="paper-quality">Quality Score: {report.quality_score}/100</p>
            )}
          </div>
        </div>

        {/* Abstract */}
        {report.summaries?.executive && (
          <div className="paper-section abstract">
            <h2>Abstract</h2>
            <p>{formatText(report.summaries.executive)}</p>
          </div>
        )}

        {/* Main Content */}
        <div className="paper-body">
          {sections.map((section, idx) => (
            <div key={idx} className="paper-section">
              {section.heading && <h2>{section.heading}</h2>}
              {section.content.map((paragraph, pIdx) => (
                <p key={pIdx}>{paragraph}</p>
              ))}
            </div>
          ))}
        </div>

        {/* Key Findings */}
        {report.summaries?.bullet && (
          <div className="paper-section key-findings">
            <h2>Key Findings</h2>
            <div className="findings-content">
              {formatText(report.summaries.bullet).split('\n').filter(line => line.trim()).map((finding, idx) => (
                <p key={idx} className="finding-item">• {finding.replace(/^[-•*]\s*/, '')}</p>
              ))}
            </div>
          </div>
        )}
      </div>
    )
  }

  const renderSummaries = () => {
    if (!report.summaries) return <p>No summaries available</p>

    return (
      <div className="research-paper">
        <div className="paper-header">
          <h1 className="paper-title">Research Summaries</h1>
        </div>

        {report.summaries.executive && (
          <div className="paper-section">
            <h2>Executive Summary</h2>
            <p>{formatText(report.summaries.executive)}</p>
          </div>
        )}

        {report.summaries.detailed && (
          <div className="paper-section">
            <h2>Detailed Summary</h2>
            <p>{formatText(report.summaries.detailed)}</p>
          </div>
        )}

        {report.summaries.bullet && (
          <div className="paper-section">
            <h2>Key Points</h2>
            {formatText(report.summaries.bullet).split('\n').filter(line => line.trim()).map((point, idx) => (
              <p key={idx}>• {point.replace(/^[-•*]\s*/, '')}</p>
            ))}
          </div>
        )}
      </div>
    )
  }

  const renderFactCheck = () => {
    if (!report.fact_check_report) return <p>No fact-check report available</p>

    return (
      <div className="research-paper">
        <div className="paper-header">
          <h1 className="paper-title">Fact Check & Verification Report</h1>
        </div>
        <div className="paper-body">
          <div className="paper-section">
            <p>{formatText(report.fact_check_report)}</p>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="report-viewer">
      <div className="report-tabs">
        <button
          className={view === 'final' ? 'active' : ''}
          onClick={() => setView('final')}
        >
          📄 Full Report
        </button>
        <button
          className={view === 'summaries' ? 'active' : ''}
          onClick={() => setView('summaries')}
        >
          📋 Summaries
        </button>
        {report.fact_check_report && (
          <button
            className={view === 'fact_check' ? 'active' : ''}
            onClick={() => setView('fact_check')}
          >
            ✓ Fact Check
          </button>
        )}
      </div>

      <div className="report-container">
        {view === 'final' && renderFinalReport()}
        {view === 'summaries' && renderSummaries()}
        {view === 'fact_check' && renderFactCheck()}
      </div>

      <style>{`
        .report-viewer {
          margin: 2rem auto;
          max-width: 1200px;
        }

        .report-tabs {
          display: flex;
          gap: 0.5rem;
          margin-bottom: 2rem;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 0.5rem;
        }

        .report-tabs button {
          background: white;
          border: 2px solid #e5e7eb;
          padding: 0.75rem 1.5rem;
          border-radius: 8px 8px 0 0;
          cursor: pointer;
          font-size: 1rem;
          font-weight: 500;
          transition: all 0.2s;
          color: #4b5563;
        }

        .report-tabs button:hover {
          background: #f9fafb;
          border-color: #667eea;
        }

        .report-tabs button.active {
          background: #667eea;
          color: white;
          border-color: #667eea;
        }

        .report-container {
          background: white;
          border-radius: 8px;
          box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05);
          overflow: hidden;
        }

        .research-paper {
          max-width: 850px;
          margin: 0 auto;
          padding: 3rem 4rem;
          background: white;
          font-family: 'Georgia', 'Times New Roman', serif;
          line-height: 1.8;
          color: #1f2937;
        }

        .paper-header {
          text-align: center;
          margin-bottom: 3rem;
          padding-bottom: 2rem;
          border-bottom: 2px solid #e5e7eb;
        }

        .paper-title {
          font-size: 2.5rem;
          font-weight: 700;
          margin-bottom: 1rem;
          color: #111827;
          line-height: 1.3;
        }

        .paper-meta {
          font-size: 0.95rem;
          color: #6b7280;
        }

        .paper-meta p {
          margin: 0.25rem 0;
        }

        .paper-date {
          font-style: italic;
        }

        .paper-quality {
          font-weight: 600;
          color: #059669;
          margin-top: 0.5rem !important;
        }

        .paper-section {
          margin-bottom: 2.5rem;
        }

        .paper-section.abstract {
          background: #f9fafb;
          padding: 1.5rem;
          border-left: 4px solid #667eea;
          border-radius: 4px;
          margin-bottom: 3rem;
        }

        .paper-section h2 {
          font-size: 1.75rem;
          font-weight: 600;
          margin-bottom: 1rem;
          color: #111827;
          border-bottom: 1px solid #e5e7eb;
          padding-bottom: 0.5rem;
        }

        .paper-section.abstract h2 {
          border: none;
          margin-bottom: 0.75rem;
        }

        .paper-body p {
          margin-bottom: 1.25rem;
          text-align: justify;
          font-size: 1.05rem;
        }

        .paper-section.key-findings {
          background: #fef3c7;
          padding: 1.5rem;
          border-left: 4px solid #f59e0b;
          border-radius: 4px;
        }

        .paper-section.key-findings h2 {
          color: #92400e;
          border-color: #f59e0b;
        }

        .finding-item {
          margin-bottom: 0.75rem;
          padding-left: 0.5rem;
          font-size: 1rem;
        }

        /* Print styles */
        @media print {
          .report-tabs {
            display: none;
          }

          .research-paper {
            padding: 0;
            max-width: 100%;
          }

          .paper-section {
            page-break-inside: avoid;
          }
        }

        /* Responsive */
        @media (max-width: 768px) {
          .research-paper {
            padding: 2rem 1.5rem;
          }

          .paper-title {
            font-size: 1.75rem;
          }

          .paper-section h2 {
            font-size: 1.4rem;
          }
        }
      `}</style>
    </div>
  )
}

export default ReportViewer